travis fix

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,23 +1,32 @@
-branches:
-  except:
-  - release
-
 matrix:
   include:
-    - os: linux
-      compiler: gcc
-      sudo: required
-      language: cpp
-      dist: trusty
-      env: BUILD_NAME=debian
     - os: osx
-      osx_image: xcode7.3
-      sudo: required
+      env: BUILD_NAME=macosx
       compiler: clang
       language: cpp
-      env: BUILD_NAME=macosx
-    - language: android
-      env: BUILD_NAME=android
+      osx_image: xcode8.2
+    - os: osx
+      env: BUILD_NAME=ios
+      compiler: clang
+      language: cpp
+      osx_image: xcode8.2
+    - os: linux
+      env: BUILD_NAME=debian
+      compiler: gcc
+      language: cpp
+      dist: trusty
+    - os: linux
+      env: BUILD_NAME=ubuntu
+      compiler: gcc
+      language: cpp
+      dist: trusty
+    - os: linux
+      env: BUILD_NAME=raspberry_pi
+      compiler: gcc
+      language: cpp
+      dist: trusty
+    - env: BUILD_NAME=android
+      language: android
 
       
 android:
@@ -32,38 +41,78 @@ android:
 
 env:
   global:
-  #encrypted PRORAB_GIT_ACCESS_TOKEN for publishing to homebrew-tap
-  - secure: "I3U740dkc/V6BNtVg/X5QPh+CLFUrthGEh78KWA4Feo6/GmLpwtQ1hbSq/Rzo4e1bVQgPxLslaGi+zYvBaje90tc62v8jwq9mgOSWdMn5zV0uoGbUSa2UclUEHLNX7pPPFbg/AKc+XpqSo9QajE/8cR83fipEJbNZYLazmMWuTEl5wwUToy6QgJxqDHpVPvYK/3JrpuO25bLkTphzp+HVV1Vob4BvyW2DGlGKXxQumM+3iNBflZ+mHB8xgJtUxRT/KMiWev6XtbeLi2cW2V4yiJeBMn9Efq+BtLs62U86u8X0QBcirFuZVGoPpS6QvEQpXysqPW21gE1U0DWSVIhXcJw79LP6Q/uCO2Zmfwwz4HqqYQQA4eof/USDdflYXsYAQP1RrSvN5RRMQ1Dg6RpXj7y9FKaSOkUPQAWkj4PtWQNes6LYXvdylElVe2pikvAdrDKWBAkl/3hS2IPVvT+eK5Kuf2npDOjBOwQJcw4kRFDeWoVH/zTVAbNTv+4a+FQ9FrCm7Zopa5H1eUV+yQZNyEicmIu/coN6/W0brMsCWg1dqM5xZTNoZaFe/DiLcsHHfp4lrOdNgMI1liYeyRExs2pe+CKegK3B//ur4y4WDl4PRf+7IvwINJjSWD7iXIkYOVdVWKJLbndrZhj5HR+8QIk+aQATmZEQFJ11+IQdH0="
-  - PRORAB_GIT_USERNAME=igagis
+  #encrypted MYCI_GIT_ACCESS_TOKEN for publishing to homebrew-tap
+  - secure: "QrMC5xtPy61Y0L3HVQoPJJ0/oGHV/mGnLmS5VlL+dyKHlTzwuLeIbUOc6yv3GyREAAH4WJXULROvxzecaKI25l1ywGReQvOv3lQ0/MFsVIYhmdMYbfgY6T1TgkBMEIZS5TFe8UzIjga4kTbjnEPQERxz/yhecl5f3/2RMX6bzgG39m79yB7LtK5cJXmX9rc8913IkAfpey9rW4L4V8adJvAo1OBlYg+dDAj7KQ/4fNtn03dffwoGV3HBuBmICeKGTomIrEbW8gtA0NFkJ43QKBIcexc4MHTYxb0vJ+ZTPDZiFTVhGMQ3VafaidLzXL5jP+YUfV+64Dd88zeo3Qpv7DHWMzrJ7EHSwK0PkwD4rlKdsbY3a1fcc+QlfXAX6HNVTMpE+f+VOXw0FGWSzRkUTmj8rfkV2DL0bZOqroqYYcBsqQlO0bIzwxu3ZuiFfnO5CYXBVLxwnnrVtYzJVyzWJwgQ2AzoS0YMfJE6SrKVevYZUMcTn8H7h10i/1VyhQyx/koLDwd1pVv/6BWDFCLpAlrHrRy+/EebthG2pJhW2fxG0fU8hM0U7dXJSG7i5NMOlj/JtEegP/nvgQOAgFocjY+fC7NNM2tETArSIBbt5qchZTX+XC2/u8YB7LydhBmphL6SlIiIjq+C8jRT8oV/XijcBhDU1+zZ52+BPyFO4tI="
+  - MYCI_GIT_USERNAME=igagis
+  - USE_ANDROID_NDK_VERSION=15c
+  - linuxDependencies="debhelper lintian pkg-config myci prorab prorab-extra doxygen libutki-dev"
 
 before_install:
-- if [ "$BUILD_NAME" == "debian" ]; then
-    echo "deb https://dl.bintray.com/igagis/deb unstable main" | sudo tee /etc/apt/sources.list.d/igagis.list > /dev/null &&
-    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61 &&
-    sudo apt-get update -qq &&
-    sudo apt-get install -qq debhelper fakeroot prorab doxygen libutki-dev;
-  fi
-- if [ "$BUILD_NAME" == "android" ]; then
-    echo "deb https://dl.bintray.com/igagis/ubu unstable main" | sudo tee /etc/apt/sources.list.d/igagis.list > /dev/null &&
-    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61 &&
-    sudo apt-get update -qq &&
-    sudo apt-get install -qq prorab;
-  fi
-# Force bundler 1.12.5 because version 1.13 has issues, see https://github.com/fastlane/fastlane/issues/6065#issuecomment-246044617
 - if [ "$BUILD_NAME" == "macosx" ]; then
-    rvm install ruby-2.2.2 &&
-    rvm use ruby-2.2.2 &&
+    rvm install ruby-2.3.3 &&
+    rvm use ruby-2.3.3 &&
     
-    rvm 2.2.1 do gem uninstall bundler -v '>1.12.5' --force &&
-    rvm 2.2.1 do gem install bundler -v 1.12.5 --no-rdoc --no-ri --no-document --quiet &&
-    
-    sudo gem install cocoapods &&
-    pod repo add --silent igagis https://$PRORAB_GIT_USERNAME:$PRORAB_GIT_ACCESS_TOKEN@github.com/igagis/cocoapods-repo.git &&
-    pod install --project-directory=ios &&
-
+    brew update > /dev/null &&
     brew tap igagis/tap &&
     brew update > /dev/null &&
-    brew install prorab libutki;
+    brew install myci prorab prorab-extra libutki;
+  fi
+- if [ "$BUILD_NAME" == "ios" ]; then
+    rvm install ruby-2.3.3 &&
+    rvm use ruby-2.3.3 &&
+    
+    brew update > /dev/null &&
+    brew tap igagis/tap &&
+    brew update > /dev/null &&
+    brew install myci &&
+    
+    sudo gem install cocoapods &&
+    pod repo add --silent igagis https://$MYCI_GIT_USERNAME:$MYCI_GIT_ACCESS_TOKEN@github.com/igagis/cocoapods-repo.git;
+  fi
+- if [ "$BUILD_NAME" == "android" ]; then
+    echo "deb [arch=amd64] https://dl.bintray.com/igagis/ubu unstable main" | sudo tee /etc/apt/sources.list.d/igagis.list > /dev/null &&
+    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61 &&
+    sudo apt-get update -qq &&
+    sudo apt-get install -qq myci;
+  fi
+- if [ "$BUILD_NAME" == "debian" ]; then
+    echo "deb [arch=amd64] http://dl.bintray.com/igagis/ubu unstable main" | sudo tee /etc/apt/sources.list.d/igagis.list > /dev/null &&
+    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61 &&
+    sudo apt-get update -qq &&
+    sudo apt-get install -qq sbuild prorab prorab-extra myci debhelper &&
+    sudo sbuild-adduser $LOGNAME &&
+    echo lQHYBFfZDkYBBACyRm0LCwK/9rSzqSJyEBihVNA61meWp9MVjn3EBPp6MV1/mjZ80LPJ6ecYX6VMu861a5yQLnlA9krUxuHxjnsEYvMQiz0zHapp8Zqu0FIvcU1IWZV7Eio5Lej7QFeHFmtPlrSqT152lVUmQFW9ZCtWOOM1KnKBhoWWLf9z7LnwSwARAQABAAP/SWyYHKQ8TbPeWOCgPzpB6rBz0sfbgkE8vvQg+ErUnt8WEygAqQeMBO1BMNizzBbN3AqmQPvjFM5bo6cGB+cW4tbmWVtp8wMGVm8dobiZP3p1YLtvrweX3gYo1P4km8B7JkeJ0oyGa1k4yP5m4+o7t97EanKLFTFCbJvV/txT+YECAMLhKBMGJBqa8766tsyXbKaHQKvUDwlVCltAbeRb/V7cnIEuf/bn5DcN2O3yhN35OX5EvCeJxtCSBDh9HkQfK0cCAOowGoepffgLuuOfnpNU3GcHU9lNsLUnYJ17Oa38z1JGjggrUvQ5V6UbH0YY14vQXbrOVn+YE9Job9UCnM6DzN0B/19ZoYzH9anOf+nmTM56Rrk8itQXhN/gpI22EZ9n8koELvYrHj3iUgPJ+BOCKTP3E9brojEC048pK58GFJkr+/qjqbRgU2J1aWxkIFNpZ25lciAoU2J1aWxkIEJ1aWxkIERlcGVuZGVuY3kgQXJjaGl2ZSBLZXkpIDxidWlsZGQtdG9vbHMtZGV2ZWxAbGlzdHMuYWxpb3RoLmRlYmlhbi5vcmc+iLgEEwECACIFAlfZDkYCGy8GCwkIBwMCBhUIAgkKCwQWAgMBAh4BAheAAAoJELG4iKvjYvQgomAEAJzhmqIVxIU3+ROL0B8Q2Iv1gWRe6X17J1UQPYIGkRYcZWYUllWjmk32snT5Yv+x2TMVojD0JCCgltU0JBvydovItd+g6H+C8I/bhoq5twC9CIYGKmhDInxwCdHG8yU7AVdEopf38VsEC+3Hazh4V5sPldHMo9Lx6u5uXiil5qKi | base64 -d | sudo tee /var/lib/sbuild/apt-keys/sbuild-key.sec > /dev/null &&
+    echo mI0EV9kORgEEALJGbQsLAr/2tLOpInIQGKFU0DrWZ5an0xWOfcQE+noxXX+aNnzQs8np5xhfpUy7zrVrnJAueUD2StTG4fGOewRi8xCLPTMdqmnxmq7QUi9xTUhZlXsSKjkt6PtAV4cWa0+WtKpPXnaVVSZAVb1kK1Y44zUqcoGGhZYt/3PsufBLABEBAAG0YFNidWlsZCBTaWduZXIgKFNidWlsZCBCdWlsZCBEZXBlbmRlbmN5IEFyY2hpdmUgS2V5KSA8YnVpbGRkLXRvb2xzLWRldmVsQGxpc3RzLmFsaW90aC5kZWJpYW4ub3JnPoi4BBMBAgAiBQJX2Q5GAhsvBgsJCAcDAgYVCAIJCgsEFgIDAQIeAQIXgAAKCRCxuIir42L0IKJgBACc4ZqiFcSFN/kTi9AfENiL9YFkXul9eydVED2CBpEWHGVmFJZVo5pN9rJ0+WL/sdkzFaIw9CQgoJbVNCQb8naLyLXfoOh/gvCP24aKubcAvQiGBipoQyJ8cAnRxvMlOwFXRKKX9/FbBAvtx2s4eFebD5XRzKPS8erubl4opeaiog== | base64 -d | sudo tee /var/lib/sbuild/apt-keys/sbuild-key.pub > /dev/null &&
+    sudo sbuild-createchroot --include=gnupg1,dirmngr,build-essential stretch /srv/chroot/deb-amd64 http://httpredir.debian.org/debian &&
+    echo "deb [trusted=yes] http://dl.bintray.com/igagis/deb unstable main" | sudo tee /srv/chroot/deb-amd64/etc/apt/sources.list.d/igagis.list > /dev/null &&
+    echo 'APT::Get { AllowUnauthenticated "1"; };' | sudo tee /srv/chroot/deb-amd64/etc/apt/apt.conf.d/80unauthenticate > /dev/null &&
+    sudo chroot /srv/chroot/deb-amd64 apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61 &&
+    sudo chroot /srv/chroot/deb-amd64 ln -s /usr/bin/gpg1 /usr/bin/gpg;
+  fi
+- if [ "$BUILD_NAME" == "ubuntu" ]; then
+    echo "deb [arch=amd64] http://dl.bintray.com/igagis/ubu unstable main" | sudo tee /etc/apt/sources.list.d/igagis.list > /dev/null &&
+    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61 &&
+    sudo apt-get update -qq &&
+    sudo apt-get install -qq sbuild myci prorab prorab-extra debhelper &&
+    sudo sbuild-adduser $LOGNAME &&
+    echo lQHYBFfZDkYBBACyRm0LCwK/9rSzqSJyEBihVNA61meWp9MVjn3EBPp6MV1/mjZ80LPJ6ecYX6VMu861a5yQLnlA9krUxuHxjnsEYvMQiz0zHapp8Zqu0FIvcU1IWZV7Eio5Lej7QFeHFmtPlrSqT152lVUmQFW9ZCtWOOM1KnKBhoWWLf9z7LnwSwARAQABAAP/SWyYHKQ8TbPeWOCgPzpB6rBz0sfbgkE8vvQg+ErUnt8WEygAqQeMBO1BMNizzBbN3AqmQPvjFM5bo6cGB+cW4tbmWVtp8wMGVm8dobiZP3p1YLtvrweX3gYo1P4km8B7JkeJ0oyGa1k4yP5m4+o7t97EanKLFTFCbJvV/txT+YECAMLhKBMGJBqa8766tsyXbKaHQKvUDwlVCltAbeRb/V7cnIEuf/bn5DcN2O3yhN35OX5EvCeJxtCSBDh9HkQfK0cCAOowGoepffgLuuOfnpNU3GcHU9lNsLUnYJ17Oa38z1JGjggrUvQ5V6UbH0YY14vQXbrOVn+YE9Job9UCnM6DzN0B/19ZoYzH9anOf+nmTM56Rrk8itQXhN/gpI22EZ9n8koELvYrHj3iUgPJ+BOCKTP3E9brojEC048pK58GFJkr+/qjqbRgU2J1aWxkIFNpZ25lciAoU2J1aWxkIEJ1aWxkIERlcGVuZGVuY3kgQXJjaGl2ZSBLZXkpIDxidWlsZGQtdG9vbHMtZGV2ZWxAbGlzdHMuYWxpb3RoLmRlYmlhbi5vcmc+iLgEEwECACIFAlfZDkYCGy8GCwkIBwMCBhUIAgkKCwQWAgMBAh4BAheAAAoJELG4iKvjYvQgomAEAJzhmqIVxIU3+ROL0B8Q2Iv1gWRe6X17J1UQPYIGkRYcZWYUllWjmk32snT5Yv+x2TMVojD0JCCgltU0JBvydovItd+g6H+C8I/bhoq5twC9CIYGKmhDInxwCdHG8yU7AVdEopf38VsEC+3Hazh4V5sPldHMo9Lx6u5uXiil5qKi | base64 -d | sudo tee /var/lib/sbuild/apt-keys/sbuild-key.sec > /dev/null &&
+    echo mI0EV9kORgEEALJGbQsLAr/2tLOpInIQGKFU0DrWZ5an0xWOfcQE+noxXX+aNnzQs8np5xhfpUy7zrVrnJAueUD2StTG4fGOewRi8xCLPTMdqmnxmq7QUi9xTUhZlXsSKjkt6PtAV4cWa0+WtKpPXnaVVSZAVb1kK1Y44zUqcoGGhZYt/3PsufBLABEBAAG0YFNidWlsZCBTaWduZXIgKFNidWlsZCBCdWlsZCBEZXBlbmRlbmN5IEFyY2hpdmUgS2V5KSA8YnVpbGRkLXRvb2xzLWRldmVsQGxpc3RzLmFsaW90aC5kZWJpYW4ub3JnPoi4BBMBAgAiBQJX2Q5GAhsvBgsJCAcDAgYVCAIJCgsEFgIDAQIeAQIXgAAKCRCxuIir42L0IKJgBACc4ZqiFcSFN/kTi9AfENiL9YFkXul9eydVED2CBpEWHGVmFJZVo5pN9rJ0+WL/sdkzFaIw9CQgoJbVNCQb8naLyLXfoOh/gvCP24aKubcAvQiGBipoQyJ8cAnRxvMlOwFXRKKX9/FbBAvtx2s4eFebD5XRzKPS8erubl4opeaiog== | base64 -d | sudo tee /var/lib/sbuild/apt-keys/sbuild-key.pub > /dev/null &&
+    sudo sbuild-createchroot --include=gnupg,dirmngr,build-essential --components=main,universe xenial /srv/chroot/ubu-amd64 http://archive.ubuntu.com/ubuntu/ &&
+    echo "deb [trusted=yes] http://dl.bintray.com/igagis/ubu unstable main" | sudo tee /srv/chroot/ubu-amd64/etc/apt/sources.list.d/igagis.list > /dev/null &&
+    sudo chroot /srv/chroot/ubu-amd64 apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61;
+  fi
+- if [ "$BUILD_NAME" == "raspberry_pi" ]; then
+    echo "deb [arch=amd64] http://dl.bintray.com/igagis/ubu unstable main" | sudo tee /etc/apt/sources.list.d/igagis.list > /dev/null &&
+    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61 &&
+    sudo apt-get update -qq &&
+    sudo apt-get install -qq myci;
+    sudo myci-make-raspberry-chroot.sh /srv/chroot/rasp-armhf &&
+    echo "deb http://dl.bintray.com/igagis/rasp unstable main" | sudo tee /srv/chroot/rasp-armhf/etc/apt/sources.list.d/igagis.list > /dev/null &&
+    sudo chroot /srv/chroot/rasp-armhf sed -i -e 's/jessie/testing/g' /etc/apt/sources.list &&
+    sudo chroot /srv/chroot/rasp-armhf apt-get update &&
+    sudo chroot /srv/chroot/rasp-armhf apt-get install --allow-unauthenticated -qq -y $linuxDependencies g++ &&
+    sudo mkdir -p /srv/chroot/rasp-armhf/build &&
+    sudo rsync -av $TRAVIS_BUILD_DIR/ /srv/chroot/rasp-armhf/build/;
   fi
 
 
@@ -71,11 +120,10 @@ before_script:
   # download and install android NDK
   - if [ "$BUILD_NAME" == "android" ]; then
       export TERM=dumb &&
-      curl -L http://dl.google.com/android/ndk/android-ndk-r10e-linux-x86_64.bin -O &&
-      chmod u+x android-ndk-r10e-linux-x86_64.bin &&
-      ./android-ndk-r10e-linux-x86_64.bin > /dev/null &&
-      rm android-ndk-r10e-linux-x86_64.bin &&
-      export ANDROID_NDK_HOME=`pwd`/android-ndk-r10e &&
+      curl -L https://dl.google.com/android/repository/android-ndk-r$USE_ANDROID_NDK_VERSION-linux-x86_64.zip -O &&
+      unzip ./android-ndk-r$USE_ANDROID_NDK_VERSION-linux-x86_64.zip > /dev/null &&
+      rm android-ndk-r$USE_ANDROID_NDK_VERSION-linux-x86_64.zip &&
+      export ANDROID_NDK_HOME=`pwd`/android-ndk-r$USE_ANDROID_NDK_VERSION &&
       export LOCAL_ANDROID_NDK_HOME="$ANDROID_NDK_HOME" &&
       export LOCAL_ANDROID_NDK_HOST_PLATFORM="linux-x86_64" &&
       export PATH=$PATH:${ANDROID_NDK_HOME} &&
@@ -84,22 +132,43 @@ before_script:
 
 script:
 - if [ "$BUILD_NAME" == "debian" ]; then
-    prorab-deb-prepare.sh &&
-    dpkg-buildpackage -us -uc;
+    myci-deb-prepare.sh &&
+    sg sbuild -c "sbuild -n -A -d stretch-amd64-sbuild --run-lintian --debbuildopts '-us -uc'";
+  fi
+- if [ "$BUILD_NAME" == "ubuntu" ]; then
+    myci-deb-prepare.sh &&
+    sg sbuild -c "sbuild -n -A -d xenial-amd64-sbuild --debbuildopts '-us -uc'";
   fi
 - if [ "$BUILD_NAME" == "macosx" ]; then
-    make &&
-    
-    xcodebuild -workspace ios/tests.xcworkspace -scheme tests CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO;
+    make;
+  fi
+# need to reduce output from xcodebuild because log size on travis-ci is limited by 4Mb, use grep for errors and warnings
+# Also, need to set pipefail to make pipe exit code nono-zero in case first command fails but second succeeds (because grep exits with 0 always)
+- if [ "$BUILD_NAME" == "ios" ]; then
+    xcodebuild -workspace ios/tests.xcworkspace -scheme tests CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
+            | sed -e "s/export PATH=[^ ]*/export PATH=.../g"
+            | sed -e "s/[^ ]*\/clang /clang /g"
+            | sed -e "s/\(-[IWfFL]\)[^ ]*/% /g"
+            | sed -e "s/-isystem [^ ]*/%/g"
+            | sed -e "s/-include [^ ]*/%/g"
+            | sed -e "s/-MF [^ ]*/%/g"
+            | sed -e "s/--serialize-diagnostics [^ ]*/%/g"
+            | sed -e "s/-o [^ ]*/%/g"
+            | sed -e "s/-iquote [^ ]*/%/g"
+            | sed -e "s/-isysroot [^ ]*/%/g";
+  fi
+- if [ "$BUILD_NAME" == "raspberry_pi" ]; then
+    sudo chroot /srv/chroot/rasp-armhf bash -c "cd /build && myci-deb-prepare.sh" &&
+    sudo chroot /srv/chroot/rasp-armhf bash -c "cd /build && dpkg-buildpackage -us -uc";
   fi
 - if [ "$BUILD_NAME" == "android" ]; then
     (cd android && ./gradlew build) &&
-    prorab-apply-version.sh -v `prorab-deb-version.sh debian/changelog` android/*.pom.in &&
-    prorab-apply-version.sh -v `prorab-deb-version.sh debian/changelog` android/*.aar.in --filename-only;
+    myci-apply-version.sh -v `myci-deb-version.sh debian/changelog` android/*.pom.in &&
+    myci-apply-version.sh -v `myci-deb-version.sh debian/changelog` android/*.aar.in --filename-only;
   fi
 
 before_deploy:
-  - prorab-apply-version.sh -v `prorab-deb-version.sh debian/changelog` travis_bintray_*.json.in
+  - myci-apply-version.sh -v `myci-deb-version.sh debian/changelog` travis_bintray_*.json.in
 
 deploy:
 - provider: bintray
@@ -144,13 +213,14 @@ deploy:
   dry-run: false
 - provider: script
   skip_cleanup: true
-  script: prorab-deploy-homebrew.sh -t igagis/tap
+  script: myci-deploy-homebrew.sh -t igagis/tap
   on:
     tags: true
     condition: $BUILD_NAME = macosx
 - provider: script
   skip_cleanup: true
-  script: rvm 2.2.1 do prorab-deploy-cocoapods.sh -r igagis
+  script: rvm 2.3.3 do myci-deploy-cocoapods.sh -r igagis
   on:
     tags: true
-    condition: $BUILD_NAME = macosx
+    condition: $BUILD_NAME = ios
+    
